// CISO Dashboard — Product / Application Name Candidates (Indian, for marketing)
// One common name for the whole platform that unifies every monitoring tool
// (SentinelOne, Checkpoint, Palo Alto, Zoho, M365, MDM, NVD, OSINT) into a
// single CISO oversight product. Each has a short meaning rooted in Indian
// languages (Sanskrit / Hindi).

export const PRODUCT_NAMES = [
  { name: 'Rakshak',          meaning: 'Sanskrit for "protector / guardian" — the platform that guards the organisation' },
  { name: 'RakshaCISO',       meaning: 'Raksha (protection) + CISO — unified protection for the security leader' },
  { name: 'Suraksha',         meaning: 'Hindi for "safety / security" — one safe view of all tools' },
  { name: 'SurakshaSetu',     meaning: 'Setu = bridge; the bridge that connects every security tool safely' },
  { name: 'ChakraView',       meaning: 'Chakra = wheel/disc; a rotating, all-seeing view of threats' },
  { name: 'ChakraShield',     meaning: 'A protective disc (like Sudarshan Chakra) over the estate' },
  { name: 'NeTra',            meaning: 'Sanskrit for "eye" — the watching eye over endpoints, mail and network' },
  { name: 'NetraCISO',        meaning: 'Netra (eye) + CISO — the seeing eye of the security office' },
  { name: 'Drishti',          meaning: 'Sanskrit for "vision / sight" — clear vision across all monitors' },
  { name: 'DrishtiBoard',     meaning: 'Drishti + dashboard; the single pane of security sight' },
  { name: 'Aakash',           meaning: 'Sanskrit for "sky / ether" — a vast, overhead watch of everything' },
  { name: 'AakashNexus',      meaning: 'Aakash + nexus; the sky-wide meeting point of all feeds' },
  { name: 'SurakshaHub',      meaning: 'A safe hub where every tool reports in' },
  { name: 'RakshakGrid',      meaning: 'A grid of protectors covering every layer' },
  { name: 'ChakraSentinel',   meaning: 'The turning wheel of sentinels guarding the org' },
  { name: 'RakshaFusion',     meaning: 'Fuses all security data under one protective name' },
  { name: 'NetraFusion',      meaning: 'One eye seeing the fused output of all monitors' },
  { name: 'Bharosa',          meaning: 'Hindi for "trust / assurance" — assured oversight for leaders' },
  { name: 'BharosaBoard',     meaning: 'A dashboard that earns the organisation’s trust' },
  { name: 'SurakshaVision',    meaning: 'A secure, far-seeing vision of risk' },
  { name: 'Tej',              meaning: 'Sanskrit for "radiance / sharpness" — sharp threat detection' },
  { name: 'TejWatch',         meaning: 'A radiant, alert watch over the estate' },
  { name: 'Aaroh',           meaning: 'Sanskrit for "ascent / rise" — raising security maturity' },
  { name: 'AarohCISO',        meaning: 'The ascent of the organisation’s security posture' },
  { name: 'Sangraha',         meaning: 'Sanskrit for "collection / aggregate" — all tools collected in one place' },
  { name: 'SangrahaSetu',     meaning: 'The bridge that gathers every security signal together' },
  { name: 'RakshaNexus',      meaning: 'The protective nexus of all integrations' },
  { name: 'DrishtiNexus',     meaning: 'The meeting point of all seen (monitored) data' },
  { name: 'ChakraVista',      meaning: 'A wide, wheeling vista of the threat landscape' },
  { name: 'NetraGrid',        meaning: 'A grid of watching eyes across endpoints and network' },
  { name: 'SurakshaSentinel',  meaning: 'The sentinel that keeps the org safe' },
  { name: 'RakshakView',      meaning: 'The protector’s view of the whole estate' },
  { name: 'BharosaNexus',     meaning: 'A trusted nexus of every security feed' },
  { name: 'AakashShield',      meaning: 'A sky-wide shield over the organisation' },
  { name: 'TejSentinel',       meaning: 'A radiant sentinel on constant alert' },
  { name: 'SangrahaCISO',      meaning: 'All CISO data aggregated into one product' },
  { name: 'ChakraCISO',        meaning: 'The CISO’s all-turning wheel of awareness' },
  { name: 'DrishtiHub',        meaning: 'A hub of clear security vision' },
  { name: 'RakshaVision',      meaning: 'Protective, far-seeing security vision' },
  { name: 'NetraSetu',        meaning: 'The bridge of watching eyes between tools and the CISO' },

  // ── More Indian-style product names ──
  { name: 'RakshakOne',        meaning: 'One protector for the entire security estate' },
  { name: 'SurakshaOne',       meaning: 'One safe, unified security product' },
  { name: 'ChakraOne',         meaning: 'One complete wheel of awareness for the CISO' },
  { name: 'NetraOne',          meaning: 'One watching eye over every integration' },
  { name: 'DrishtiOne',        meaning: 'One clear vision across all monitors' },
  { name: 'AakashOne',         meaning: 'One sky-wide view of the organisation' },
  { name: 'BharosaOne',        meaning: 'One trusted source of security truth' },
  { name: 'SangrahaOne',       meaning: 'One place where all security data is gathered' },
  { name: 'TejOne',            meaning: 'One sharp, radiant detection product' },
  { name: 'AarohOne',          meaning: 'One platform to raise security maturity' },
  { name: 'RakshaView',        meaning: 'The protector’s live view of risk' },
  { name: 'SurakshaView',      meaning: 'A safe, live view for leadership' },
  { name: 'NetraView',         meaning: 'The eye’s view across endpoints and network' },
  { name: 'DrishtiView',       meaning: 'Clear sight of every threat in one pane' },
  { name: 'ChakraViewX',       meaning: 'An expanded, all-seeing wheel of monitoring' },
  { name: 'AakashView',        meaning: 'A sky-wide, overhead monitoring view' },
  { name: 'BharosaView',       meaning: 'A trusted, reassuring view of posture' },
  { name: 'SangrahaView',      meaning: 'The gathered view of all tools' },
  { name: 'TejView',           meaning: 'A radiant, sharp security view' },
  { name: 'AarohView',         meaning: 'An ascending view of maturity' },
  { name: 'RakshaHub',         meaning: 'A protective hub of all feeds' },
  { name: 'SurakshaHub',       meaning: 'A safe hub where tools report in' },
  { name: 'NetraHub',          meaning: 'The eye’s hub of monitoring' },
  { name: 'DrishtiHub',        meaning: 'A hub of clear security vision' },
  { name: 'ChakraHub',         meaning: 'A hub built on the wheel of awareness' },
  { name: 'AakashHub',         meaning: 'A sky-wide hub of oversight' },
  { name: 'BharosaHub',        meaning: 'A trusted hub of every signal' },
  { name: 'SangrahaHub',       meaning: 'The aggregate hub of all data' },
  { name: 'TejHub',            meaning: 'A radiant hub of detection' },
  { name: 'AarohHub',          meaning: 'A hub that lifts security posture' },
  { name: 'RakshaNexus',       meaning: 'The protective nexus of integrations' },
  { name: 'SurakshaNexus',     meaning: 'A safe meeting point of all feeds' },
  { name: 'NetraNexus',        meaning: 'The eye’s nexus of watching' },
  { name: 'DrishtiNexus',      meaning: 'The nexus of all seen data' },
  { name: 'ChakraNexus',       meaning: 'The wheel’s nexus of awareness' },
  { name: 'AakashNexus',       meaning: 'A sky-wide nexus of monitoring' },
  { name: 'BharosaNexus',      meaning: 'A trusted nexus of every feed' },
  { name: 'SangrahaNexus',     meaning: 'The aggregate nexus of all tools' },
  { name: 'TejNexus',          meaning: 'A radiant nexus of detection' },
  { name: 'AarohNexus',        meaning: 'A nexus that raises maturity' },
  { name: 'RakshaFusion',      meaning: 'Fuses all security data under protection' },
  { name: 'SurakshaFusion',    meaning: 'A safe fusion of every tool' },
  { name: 'NetraFusion',       meaning: 'One eye seeing fused monitor output' },
  { name: 'DrishtiFusion',     meaning: 'Clear vision from fused data' },
  { name: 'ChakraFusion',      meaning: 'The wheel’s fusion of awareness' },
  { name: 'AakashFusion',      meaning: 'Sky-wide fusion of all signals' },
  { name: 'BharosaFusion',     meaning: 'Trusted fusion of every feed' },
  { name: 'SangrahaFusion',    meaning: 'Aggregated fusion of all tools' },
  { name: 'TejFusion',         meaning: 'Radiant fusion of detection data' },
  { name: 'AarohFusion',       meaning: 'Fusion that lifts security maturity' },
  { name: 'RakshaSentinel',    meaning: 'The sentinel that keeps the org safe' },
  { name: 'SurakshaSentinel',  meaning: 'A safe sentinel on constant watch' },
  { name: 'NetraSentinel',     meaning: 'The eye-sentinel over the estate' },
  { name: 'DrishtiSentinel',   meaning: 'The clear-sighted sentinel' },
  { name: 'ChakraSentinelX',   meaning: 'The wheel’s sentinel of awareness' },
  { name: 'AakashSentinel',    meaning: 'A sky-wide sentinel of oversight' },
  { name: 'BharosaSentinel',   meaning: 'A trusted sentinel for leaders' },
  { name: 'SangrahaSentinel',  meaning: 'The gathering sentinel of all data' },
  { name: 'TejSentinel',       meaning: 'A radiant sentinel on alert' },
  { name: 'AarohSentinel',     meaning: 'A sentinel that lifts posture' },
  { name: 'RakshaGrid',        meaning: 'A grid of protectors across layers' },
  { name: 'SurakshaGrid',      meaning: 'A safe grid covering the estate' },
  { name: 'NetraGrid',         meaning: 'A grid of watching eyes' },
  { name: 'DrishtiGrid',       meaning: 'A grid of clear security sight' },
  { name: 'ChakraGrid',        meaning: 'A grid built on the wheel of awareness' },
  { name: 'AakashGrid',        meaning: 'A sky-wide grid of oversight' },
  { name: 'BharosaGrid',       meaning: 'A trusted grid of monitoring' },
  { name: 'SangrahaGrid',      meaning: 'The aggregate grid of all tools' },
  { name: 'TejGrid',           meaning: 'A radiant grid of detection' },
  { name: 'AarohGrid',         meaning: 'A grid that raises maturity' },
  { name: 'RakshaBoard',       meaning: 'The protector’s dashboard' },
  { name: 'SurakshaBoard',     meaning: 'A safe security dashboard' },
  { name: 'NetraBoard',        meaning: 'The eye’s dashboard of watch' },
  { name: 'DrishtiBoard',      meaning: 'A dashboard of clear vision' },
  { name: 'ChakraBoard',       meaning: 'A dashboard on the wheel of awareness' },
  { name: 'AakashBoard',       meaning: 'A sky-wide oversight dashboard' },
  { name: 'BharosaBoard',      meaning: 'A trusted leadership dashboard' },
  { name: 'SangrahaBoard',     meaning: 'The aggregate dashboard of all tools' },
  { name: 'TejBoard',          meaning: 'A radiant detection dashboard' },
  { name: 'AarohBoard',        meaning: 'A dashboard that lifts maturity' },
  { name: 'RakshaSphere',      meaning: 'A protective sphere around the org' },
  { name: 'SurakshaSphere',    meaning: 'A safe sphere of oversight' },
  { name: 'NetraSphere',       meaning: 'A sphere of watching eyes' },
  { name: 'DrishtiSphere',     meaning: 'A sphere of clear vision' },
  { name: 'ChakraSphere',      meaning: 'A sphere on the wheel of awareness' },
  { name: 'AakashSphere',      meaning: 'A sky-wide sphere of monitoring' },
  { name: 'BharosaSphere',     meaning: 'A trusted sphere of signals' },
  { name: 'SangrahaSphere',    meaning: 'The aggregate sphere of all data' },
  { name: 'TejSphere',         meaning: 'A radiant sphere of detection' },
  { name: 'AarohSphere',       meaning: 'A sphere that lifts posture' },
];
